server:
  port: 8000
#spring:
#  security:
#    user:
#      name: user
#      password: password

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://mysql.qctc.com:3306/js_produce?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    #    username: js_produce
    #    password: js_produce
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://mysql.eboss.qctc.com:5236/LXDD_YXFS_QCTC
    username: LXDD_YXFS_QCTC
    password: Qctc.6608